name: 'Use flippy script to package Armvirt as OpenWrt'
author: 'ophub'
description: 'Package Armvirt as OpenWrt. Support Amlogic S9xxx STB, vplus, beikeyun and l1pro, etc.'
inputs:
  mode:
    description: 'Choose script.'
    required: false
    default: 'flippy'

runs:
  using: "composite"
  steps: 
    - run: ${GITHUB_ACTION_PATH}/openwrt_${{ inputs.mode }}.sh
      shell: bash
      
branding:
  icon: 'terminal'
  color: 'gray-dark'
  
- name: Upload OpenWrt Firmware to Release
  uses: ncipollo/release-action@main
  with:
    tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
    artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
    allowUpdates: true
    token: ${{ secrets.GH_TOKEN }}
    body: |
      This is OpenWrt firmware for Armvirt 64
      * Firmware information
      Default IP: 192.168.1.1
      Default username: root
      Default password: password
